-- Drop the existing outdated table structure
DROP TABLE IF EXISTS tribal_lore;

-- Create the clean, dedicated table for Tribal Lore
CREATE TABLE tribal_lore (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tribe_name TEXT NOT NULL,
    entity_name TEXT NOT NULL,
    states_present TEXT[] NOT NULL,
    synopsis TEXT NOT NULL,
    source_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert verified regional traditions
INSERT INTO tribal_lore (tribe_name, entity_name, states_present, synopsis, source_url)
VALUES 
(
    'Eastern Band of Cherokee',
    'Tsul ''Kalu (Slant-Eyed Giant)',
    ARRAY['NC', 'TN', 'GA', 'SC', 'VA'],
    'Cherokee oral history speaks of Tsul ''Kalu, a reclusive, hair-covered mountain spirit and master of game animals who inhabits high balds and deep timberlands.',
    'https://www.cherokeeheritage.org/'
),
(
    'Coast Salish / Halkomelem',
    'Sasq''ets (Wild Man of the Woods)',
    ARRAY['WA', 'OR', 'BC'],
    'Primary linguistic origin of "Sasquatch." Salish traditions record Sasq''ets as reclusive nocturnal wilderness caretakers residing deep in high mountain ranges.',
    'https://www.stsailes.com/'
),
(
    'Choctaw Nation',
    'Lofa (Hairy Mountain Being)',
    ARRAY['OK', 'MS', 'AL'],
    'Choctaw accounts describe the Lofa as a solitary, hairy creature inhabiting deep river bottoms and dense pine thickets.',
    'https://www.choctawnation.com/'
),
(
    'Klamath / Modoc',
    'Matah Kagmi (Keepers of the Forest)',
    ARRAY['CA', 'OR'],
    'Klamath traditions include reclusive, powerful forest beings who live high in the Cascade mountains and protect wild game.',
    'https://klamathtribes.org/'
);
